##Definindo a porta em que a aplicação vai rodar 
server:
  port: 8888

##Definindo o nome da aplicação 
spring:
  application:
    name: ead-config-server
    
## se cadastrando no eureka 
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'    
  instance:
    hostname: localhost 

