##Definindo a porta em que a aplicação vai rodar 
server:
  port: 8888

##Definindo o nome da aplicação 
spring:
  application:
    name: ead-config-server

ead:
  configService:
    username: configserver
    password: 'Config123'  
  serviceRegistry:
    username: serviceregistry
    password: 'Lucas123'

    
## se cadastrando no eureka 
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'    
  instance:
    hostname: localhost 

